routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'ChapterController@index');

Auth::routes();

//untuk laravel file manager tinymce
Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::get('home', 'HomeController@index')->name('home');
Route::resource('profile', 'ProfileController');
Route::get('chapters', 'ChapterController@index')->name('chapter.index');
Route::resource('books/{book}/chapter', 'ChapterController')->except(['index']);
Route::resource('books', 'BookController');
Route::post('bookmark', 'BookController@saveBookmark');
Route::delete('bookmark', 'BookController@removeBookmark');


Route::get('/webcrawler', 'WebCrawlerController@index')->name('webcrawler.index');
Route::post('/webcrawler/book', 'WebCrawlerController@fetchBook')->name('webcrawler.book');
Route::post('/webcrawler/book/save', 'WebCrawlerController@saveBook');
Route::post('/webcrawler/chapter/save', 'WebCrawlerController@saveChapters');
Route::get('/webcrawler/chapter/{url}', 'WebCrawlerController@fetchChapter')->name('webcrawler.chapter')->where('url', '.*');

resources/views/adminlte/partials/breadcrumbs.blade.php
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-12">
            <ol class="breadcrumb float-sm-right">
                <!-- @php 
                $path = "";
                if ($breadcrumbs) {
                    echo '<li class="breadcrumb-item"><a href="/">Home</a></li>';
                } else {
                    echo '<li class="breadcrumb-item active">Home</li>';
                }
                @endphp

                @foreach ($breadcrumbs as $index => $breadcrumb)
                    @php 
                    $path = $path .'/'. $breadcrumb;
                    if ($index == count($breadcrumbs)-1){
                        echo '<li class="breadcrumb-item active">'. $breadcrumb .'</li>';
                    } else {
                        echo '<li class="breadcrumb-item"><a href="'. $path .'">'. $breadcrumb .'</a></li>';
                    }
                    @endphp
                @endforeach -->
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

resources/views/adminlte/partials/footer.blade.php
  <footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 3.0.5
    </div>
    <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">Web Reader</a>.</strong> All rights
    reserved.
  </footer>

resources/views/adminlte/partials/navbar.blade.php
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="/" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{ asset('/adminlte/dist/img/user1-128x128.jpg')}} " alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{ asset('/adminlte/dist/img/user8-128x128.jpg')}} " alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{ asset('/adminlte/dist/img/user3-128x128.jpg')}} " alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

resources/views/adminlte/partials/sidebar.blade.php
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a href="/" class="brand-link">
    <img src="{{ asset('/adminlte/dist/img/AdminLTELogo.png')}} " alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
    <span class="brand-text font-weight-light">Web Reader</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user (optional) -->
    @guest
    <div class="user-panel mt-3 pb-3 mb-3 d-flex justify-content-around">
      <div class="nav">
        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
      </div>
      @if (Route::has('register'))
      <div class="nav">
        <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
      </div>
      @endif
    </div>
    @else
    <div class="user-panel my-3 pb-3">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
              with font-awesome or any other icon font library -->
        <li class="nav-item has-treeview">
          <a href="#" class="nav-link py-2 px-0">
            <div class="image mr-2">
              @if ( Auth::user()->profile->photo )
              <img src="{{ Auth::user()->profile->photo }}" style="height:33.6px; width:33.6px" class="img-circle" alt="Profile Photo">
              @else
              <h3 class="img-circle text-center align-middle" style="height:33.6px; width:33.6px; background-color:rgb({{rand(10,180)}},{{rand(10,180)}},{{rand(10,180)}})">
                {{ strtoupper(Auth::user()->name)[0] }}
              </h3>
              @endif
            </div>
            <p class="align-middle">
              <p style="display:inline; font-size:1.3rem;">
                {{ '@'. Auth::user()->name }}
              </p>
              <i class="fas fa-angle-left right" style="top:1.2rem;"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a class="nav-link" href="{{ route('profile.show', ['profile'=>Auth::user()->name]) }}">
                <i class="far fa-circle nav-icon"></i>
                <p>Profile</p>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ route('logout') }}" onclick="event.preventDefault();
                                  document.getElementById('logout-form').submit();">
                <i class="far fa-circle nav-icon"></i>
                <p>{{ __('Logout') }}</p>
              </a>

              <form id="logout-form" style="z-index:5;" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
              </form>
            </li>
          </ul>
        </li>
      </ul>
    </div>
    @endguest
    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
        <li class="nav-item has-treeview menu-open">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-table"></i>
            <p>
              Pages
              <i class="fas fa-angle-left right"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{{ route('profile.index') }}" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Profiles</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{{ route('books.index') }}" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Books</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{{ route('chapter.index') }}" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Chapters</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{{ route('webcrawler.index') }}" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>WebScrap</p>
              </a>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>