routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'ChapterController@index');

Auth::routes();

//untuk laravel file manager tinymce
Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::get('home', 'HomeController@index')->name('home');
Route::resource('profile', 'ProfileController');
Route::get('chapters', 'ChapterController@index')->name('chapter.index');
Route::resource('books/{book}/chapter', 'ChapterController')->except(['index']);
Route::resource('books', 'BookController');
Route::post('bookmark', 'BookController@saveBookmark');
Route::delete('bookmark', 'BookController@removeBookmark');


Route::get('/webcrawler', 'WebCrawlerController@index')->name('webcrawler.index');
Route::post('/webcrawler/book', 'WebCrawlerController@fetchBook')->name('webcrawler.book');
Route::post('/webcrawler/book/save', 'WebCrawlerController@saveBook');
Route::post('/webcrawler/chapter/save', 'WebCrawlerController@saveChapters');
Route::get('/webcrawler/chapter/{url}', 'WebCrawlerController@fetchChapter')->name('webcrawler.chapter')->where('url', '.*');

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use App\User;
use App\Bookmark_User;

class Book extends Model
{
    protected $guarded = [];
    // protected $attributes = [
    //     'author_id' => '',
    // ];
    //ini untuk one to many ke chapters
    public function chapters()
    {
        return $this->hasMany('App\Chapter')->orderby('published_date');
    }
    //ini untuk many to many ke tags
    public function tags()
    {
        return $this->belongsToMany('App\Tag', 'books_tags');
    }
    //ini untuk one to many inverse ke users
    public function author()
    {
        return $this->belongsTo('App\User', 'author_id');
    }

    //ini untuk many to many ke users
    public function users()
    {
        return $this->belongsToMany('App\User', 'bookmarks_users');
    }

    //ini untuk check kalo buku di bookmark oleh user
    public function bookmarked($user_id)
    {
        return $this->users->find(User::find($user_id));
    }

    //ini untuk check last read chapter oleh user
    public function lastRead($user_id)
    {

        $bookmark = Bookmark_User::where([
            ['user_id', $user_id],
            ['book_id', $this->id]
            ])->first();
            
        if ($bookmark){
            return $bookmark->chapter;
        } else {
            return null;
        }
    }

    //ini untuk check latest chapter oleh user
    public function latestChapters()
    {
        return $this->chapters->last();
    }

}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;
// use RealRashid\SweetAlert\Facades\Alert;

use Illuminate\Http\Request;
use App\Tag;
use Auth;
use App\Book;
use App\Chapter;
use App\Book_Tag;
use App\Bookmark_User;
use DB;
use RealRashid\SweetAlert\Facades\Alert;


class BookController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth')->only('create', 'edit', 'update', 'store');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $books = Book::all();
        return view('book.index', compact('books'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('book.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $tag_ids = [];
        $tags_arr = explode(',', $request["tags"]);
        foreach ($tags_arr as $tag_name) {
            $tag = Tag::firstOrCreate(['name' => $tag_name]);
            $tag_ids[] = $tag->id;
        }
        $book = Book::create([
            'title' => $request['title'],
            'summary' => $request['summary'],
            'author_id' => Auth::id()
        ]);

        $book->tags()->sync($tag_ids);
        Alert::success('Berhasil', 'Berhasil Menambah Buku Baru');

        return redirect('/books');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $book = Book::find($id);
        return view('book.show', compact('book'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = Auth::user();
        $book = Book::find($id);
        if ($book->author_id == $user->id) {
            return view('book.edit', compact('book'));
        } else {
            Alert::warning('Error', 'You cant Edit other people book');
            return view('book.show', compact('book'));
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $update = Book::where('id', $id)->update([
            'title' => $request['title'],
            'summary' => $request['summary']
        ]);
        Alert::success('Berhasil', 'Berhasil Mengedit Buku');
        return redirect('/books');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = Auth::user();
        $book = Book::find($id);
        
        if ($book->author_id == $user->id) {
            $booktag = Book_Tag::where('book_id', $book->id)->delete();
            $chapter = Chapter::where('book_id', $book->id)->delete();
            $bookmarks = Bookmark_User::where('book_id', $book->id)->delete();


            Book::destroy($id);
            Alert::success('Berhasil', 'Berhasil Menghapus Buku');
            return redirect('/books');
        } else {
            Alert::warning('Error', 'You cant Delete other people book');
        }
    }

    public function saveBookmark(Request $request)
    {
        $bookmark_check = Bookmark_User::where([
            ['user_id', Auth::user()->id],
            ['book_id', $request['book_id']]
            ])->first();
            // dd($bookmark_check);
        if (!$bookmark_check) {
            $bookmark_user = Bookmark_User::create([
                'user_id' => Auth::user()->id,
                'book_id' => $request['book_id'],
                'chapter_id' => $request['chapter_id'] ?? null
            ]);
            Alert::success('Berhasil', 'Berhasil menyimpan bookmark');
        } else {
            Alert::warning('Gagal', 'Sudah ada di daftar bookmark anda');
        }

        if ($request['chapter_id'] != ''){
            $book = Book::find($request['book_id']);
            $chapter = Chapter::find($request['chapter_id']);
            return redirect(route('chapter.show', ['book' => $book, 'chapter' => $chapter]));
        } else {
            $book = Book::find($request['book_id']);
            return redirect(route('books.show', ['book' => $book]));
        }
    }

    public function removeBookmark(Request $request)
    {
        $bookmark_check = Bookmark_User::where([
            ['user_id', Auth::user()->id],
            ['book_id', $request['book_id']]
            ])->delete();
        
        if ($request['chapter_id'] != ''){
            $book = Book::find($request['book_id']);
            $chapter = Chapter::find($request['chapter_id']);
            return redirect(route('chapter.show', ['book' => $book, 'chapter' => $chapter]));
        } else {
            $book = Book::find($request['book_id']);
            return redirect(route('books.show', ['book' => $book]));
        }
    }
}

resources/views/book/create.blade.php
@extends('adminlte.master')
@push('script-tiny')
    <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
@endpush
@section('content')
    <div class="mx-2 mt-2">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Create New Book</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form role="form" action="/books" method="POST">
                @csrf
                <div class="card-body">
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" class="form-control" id="title" value="{{ old('title', '') }}" name="title"
                            placeholder="Insert title" required>
                        @error('title')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="summary">Summary</label>
                        {{-- <input type="text" class="form-control" id="summary" value="{{ old('summary', '') }}" name="summary"
                            placeholder="Insert summary" required> --}}
                            <textarea name="summary" class="form-control my-editor">{!! old('summary', $summary ?? '') !!}</textarea>
                        @error('summary')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="tags">Tags</label>
                        <input type="text" class="form-control" id="tags" value="{{ old('tags', '') }}" name="tags"
                            placeholder="Insert Tags with comma separator" required>
                        @error('tags')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Buat</button>
                </div>
            </form>
        </div>

    </div>
@endsection

@push('scripts')
    <script>
        var editor_config = {
            path_absolute: "/",
            selector: "textarea.my-editor",
            plugins: [
                "advlist autolink lists link image charmap print preview hr anchor pagebreak",
                "searchreplace wordcount visualblocks visualchars code fullscreen",
                "insertdatetime media nonbreaking save table contextmenu directionality",
                "emoticons template paste textcolor colorpicker textpattern"
            ],
            toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
            relative_urls: false,
            file_browser_callback: function(field_name, url, type, win) {
                var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName(
                    'body')[0].clientWidth;
                var y = window.innerHeight || document.documentElement.clientHeight || document
                    .getElementsByTagName('body')[0].clientHeight;

                var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
                if (type == 'image') {
                    cmsURL = cmsURL + "&type=Images";
                } else {
                    cmsURL = cmsURL + "&type=Files";
                }

                tinyMCE.activeEditor.windowManager.open({
                    file: cmsURL,
                    title: 'Filemanager',
                    width: x * 0.8,
                    height: y * 0.8,
                    resizable: "yes",
                    close_previous: "no"
                });
            }
        };

        tinymce.init(editor_config);

    </script>
@endpush

resources/views/book/edit.blade.php
@extends('adminlte.master')
@push('script-tiny')
    <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
@endpush
@section('title', $book->title )

@section('content')
    <div class="mx-2 mt-2">
        <div class="card card-primary">
            <div class="card-header">
                <div class="d-flex justify-content-between">
                    <div class="p-0">
                        <h4>Edit Book</h4>
                    </div>
                    <div class="p-0">
                        <form action="{{route('books.destroy', ['book'=>$book->id])}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button type="submit" value="delete" class="btn btn-danger btn-sm">Delete this Book</button>
                        </form>
                    </div>
                </div>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form role="form" action="/books/{{ $book->id }}" method="POST">
                @csrf
                @method('PUT')
                <div class="card-body">
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" class="form-control" id="title" value="{{ old('title', $book->title) }}"
                            name="title" placeholder="Insert title" required>
                        @error('title')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="summary">Summary</label>
                        {{-- <input type="text" class="form-control" id="summary" value="{{ old('summary', $book->summary) }}"
                            name="summary" placeholder="Insert Summary" required> --}}
                            <textarea name="summary" class="form-control my-editor">{!! old('summary', $book->summary ?? '') !!}</textarea>

                        @error('summary')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>

    </div>
@endsection

@push('scripts')
    <script>
        var editor_config = {
            path_absolute: "/",
            selector: "textarea.my-editor",
            plugins: [
                "advlist autolink lists link image charmap print preview hr anchor pagebreak",
                "searchreplace wordcount visualblocks visualchars code fullscreen",
                "insertdatetime media nonbreaking save table contextmenu directionality",
                "emoticons template paste textcolor colorpicker textpattern"
            ],
            toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
            relative_urls: false,
            file_browser_callback: function(field_name, url, type, win) {
                var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName(
                    'body')[0].clientWidth;
                var y = window.innerHeight || document.documentElement.clientHeight || document
                    .getElementsByTagName('body')[0].clientHeight;

                var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
                if (type == 'image') {
                    cmsURL = cmsURL + "&type=Images";
                } else {
                    cmsURL = cmsURL + "&type=Files";
                }

                tinyMCE.activeEditor.windowManager.open({
                    file: cmsURL,
                    title: 'Filemanager',
                    width: x * 0.8,
                    height: y * 0.8,
                    resizable: "yes",
                    close_previous: "no"
                });
            }
        };

        tinymce.init(editor_config);

    </script>
@endpush

resources/views/book/index.blade.php
@extends('adminlte.master')

@section('title', 'Books')

@section('content')
    <div class="row">
        <div class="col-md-6 col-lg-4 col-sm-12 p-2">
            <div class="card h-100" style="transform:rotate(0);">
                <div class="align-middle d-flex justify-content-center align-items-center" style="height:100%;">
                    <div>
                        <i class="fas fa-pencil-alt fa-5x" style="width:100%; text-align:center;"></i>
                        <a class="stretched-link" style="display:block;" href="{{ route('books.create') }}">Write Book</a>
                    </div>
                </div>
            </div>
        </div>
    @forelse ($books as $key => $item)
        <div class="col-md-6 col-lg-4 col-sm-12 p-2">
            <div class="card h-100" style="transform:rotate(0);">
                <div class="card-header">
                        <h3 class="card-title">{{ $item->title }}</h3>
                </div>
                <div class="card-body" style="height: 18rem; overflow: hidden; text-overflow: ellipsis;">
                    <div class="card-text">
                        {!! $item->summary !!}
                    </div>
                </div>
                <div class="card-footer">
                    <a class="stretched-link" href="{{ route('books.show', ['book'=>$item->id]) }}">
                        Read
                    </a>
                </div>
            </div>
        </div>
    @empty
    @endforelse
    </div>
@endsection

resources/views/book/show.blade.php
@extends('adminlte.master')

@section('title', $book->title)

@section('content')
    <div class="card">
        <div class="card-header">
            <div class="d-flex justify-content-between">
                <div class="p-0">
                    <h3>{{ $book->title }}</h3>
                </div>
                <div class="p-0 d-flex">
                @guest
                @else
                    @if( $book->bookmarked(Auth::user()->id) )
                        <form action="{{ action('BookController@removeBookmark') }}" method="POST">
                        @csrf
                        @method("DELETE")
                            <input id="checked_chapters" type="hidden" value="{{$book->id}}" name="book_id">
                            <input id="checked_chapters" type="hidden" value="" name="chapter_id">
                            <button id="fetch_chapters" type="submit" class="btn btn-primary">
                                <i class="fas fa-bookmark fa-sm"></i>
                            </button>
                        </form>
                    @else
                        <form action="{{ action('BookController@saveBookmark') }}" method="POST">
                        @csrf
                            <input id="checked_chapters" type="hidden" value="{{$book->id}}" name="book_id">
                            <input id="checked_chapters" type="hidden" value="" name="chapter_id">
                            <button id="fetch_chapters" type="submit" class="btn btn-primary">
                                <i class="far fa-bookmark fa-sm"></i>
                            </button>
                        </form>
                    @endif
                    @if(Auth::user()->id == $book->author->id)
                    <form action="{{route('books.edit', ['book'=>$book->id])}}">
                        <button id="edit_book" type="submit" class="btn btn-primary ml-2">
                            <i class="fas fa-pencil-alt fa-sm"></i>
                            Edit
                        </button>
                    </form>
                    @endif
                @endguest
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="card-text">
            {!! $book->summary !!}
            </div>
        </div>
        <div class="card-footer">
            Tags :
            @forelse($book->tags as $tag)
                <button class="btn btn-primary">{{ $tag->name }}</button>
            @empty
                No Tags
            @endforelse
        </div>
    </div>

    
    <div class="card">
        <div class="card-header">
            <div class="d-flex justify-content-between">
                <div class="p-0">
                    <h3>Chapters</h3>
                </div>
                @guest
                @else
                    @if(Auth::user()->id == $book->author->id)
                    <div class="p-0">
                        <a class="btn btn-primary" href="{{route('chapter.create', ['book' => $book->id])}}"> Write New Chapter</a>
                    </div>
                    @endif
                @endguest
            </div>
        </div>
        <div class="card-body">
            <table id="chapter-list" class="table table-borderless">
                <thead>
                    <tr>
                        <th style="width: 10px">#</th>
                        <th>Chapter</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse( $book->chapters as $key => $chapter )
                        <tr style="transform:rotate(0);">
                            <td>{{ $key+1 }}</td>
                            <td><a class="stretched-link" href="{{route('chapter.show', ['book' => $book->id, 'chapter' => $chapter->id])}}">{{ $chapter->title }}</a></td>
                        </tr>
                        @empty
                        <tr>
                            <td colspan="3"> No Chapter Data Found. </td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>

@endsection